apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitterbackend-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitterbackend-project
  template:
    metadata:
      labels:
        app: twitterbackend-project
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.3
          env:
            - name: MYSQL_DATABASE
              value: Tweet_DB
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: mypass
          ports:
            - containerPort: 3306
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
        - name: translate
          image: twitterbackend-translate
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
            - containerPort: 8000
        - name: tweet-ms
          image: twitterbackend-tweet_ms
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
