version: "3"
services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=
      - MYSQL_DATABASE=user_service_db
      - MYSQL_ROOT_PASSWORD=Allahho123
  userauth:
    build: .
    ports:
      - "8082:8082"
    environment:
      - spring.data.host=localhost
    depends_on:
      - mariadb
