version: '3.8'

services:
  tweet_ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app/tweet_ms
    depends_on:
      - mariadb
    environment:
      - WSDL_URL=http://translate:9000/?wsdl

      
  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=Tweet_DB
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - "3306:3306"
      
  translate:
    build:
      context: ../translate_service/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    