version: '3.8'

services:
  tweet_ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mariadb
      
  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=Tweet_DB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - "3306:3306"
      
  